language: php

sudo: false

env:
  global:
    - RUN_PHPCS="no"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"

matrix:
  include:
    - php: 5.4
      env: INSTALL_APC="yes"
    - php: 5.5
      env: INSTALL_APCU="yes"
    - php: 5.6
      env: RUN_PHPCS="yes" INSTALL_APCU="yes"
    - php: 7.0
      env: INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled apcu_bc install until https://github.com/travis-ci/travis-ci/issues/5303 is resolved
    - php: hhvm
      env: INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no"
  allow_failures:
    - php: hhvm

services:
  - memcache
  - memcached

before_script:
  - composer install
  # Enable additional PHP extensions
  - if [ "$INSTALL_MEMCACHE" == "yes" ]; then phpenv config-add .travis/phpenv/memcache.ini; fi
  - if [ "$INSTALL_MEMCACHED" == "yes" ]; then phpenv config-add .travis/phpenv/memcached.ini; fi
  - if [ "$INSTALL_APC" == "yes" ]; then phpenv config-add .travis/phpenv/apc-$TRAVIS_PHP_VERSION.ini; fi
  - if [ "$INSTALL_APCU" == "yes" ]; then printf "\n" | pecl install apcu-4.0.10; fi
  - if [ "$INSTALL_APCU_BC_BETA" == "yes" ]; then printf "\n" | pecl install apcu_bc-beta; fi

script:
  - vendor/bin/phpunit
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/; fi;
